projectroom/urls.py
__author__ = 'christian'

from django.conf.urls import url, include
from django.contrib.auth.views import logout, login
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

import views

admin.autodiscover()

urlpatterns = [
    url(r'^$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^projects$', views.ProjectListView.as_view(), name='project_list'),
    url(r'^closed', views.ClosedJobsListView.as_view(), name='closed_jobs'),
    url(r'^login$', login, {'template_name': 'projectroom/login.html'}, name="pr_login"),
    url(r'^logout$', logout, {'template_name': 'projectroom/logout.html'}, name="pr_logout"),
    #url(r'^(?P<slug>[-\w]+)/$', views.ProjectDetailView.as_view(), name='project'),
    url(r'^(?P<project__slug>[-\w]+)/jobs$', views.JobListView.as_view(), name='job_list'),
    url(r'^(?P<project__slug>[-\w]+)/jobs/add$', views.JobCreateView.as_view(), name='job_add'),
    url(r'^(?P<project__slug>[-\w]+)/job/(?P<pk>[\d]+)$', views.JobDetailView.as_view(), name='job'),
    url(r'^(?P<project__slug>[-\w]+)/job/(?P<pk>[\d]+)/edit$', views.JobUpdateView.as_view(), name='job_edit'),
    url(r'^(?P<project__slug>[-\w]+)/job/(?P<pk>[\d]+)/add', views.TicketCreateView.as_view(), name='ticket_add'),
    url(r'^(?P<project__slug>[-\w]+)/job/(?P<job__pk>[\d]+)/ticket/(?P<pk>[\d]+)$', views.TicketDetailView.as_view(), name='ticket'),
    url(r'^(?P<project__slug>[-\w]+)/job/(?P<job__pk>[\d]+)/ticket/(?P<pk>[\d]+)/edit$', views.TicketEditView.as_view(), name='ticket_edit'),
    url(r'^(?P<project__slug>[-\w]+)/job/(?P<job__pk>[\d]+)/ticket/(?P<pk>[\d]+)/add$', views.TicketItemCreateView.as_view(), name='ticketitem_add'),
    #(r'^js/(?P<script>[-\w]+)\.js', 'finance.views.js'),
    #(r'^json/', 'finance.views.json')
    #(r'^json/(?P<action>[-\w]+)/$', 'finance.views.json'),
    #url(r'^portal\.js', 'arp_portal.views.portal_js', name="portal_js"),
    #url(r'^grid\.js', 'arp_portal.views.portal_grid', name="portal_grid"),
    #url(r'^portal/usermenu/', 'arp_portal.views.usermenu', name="portal_usermenu"),
    #url(r'^portal/posts/', 'arp_portal.views.posts', name="portal_posts"),
    #url(r'^portal/users/', 'arp_portal.views.userlist', name="portal_userlist")
    #(r'^articles/(\d{4})/$', 'news.views.year_archive'),
    #(r'^articles/(\d{4})/(\d{2})/$', 'news.views.month_archive'),
    #(r'^articles/(\d{4})/(\d{2})/(\d+)/$', 'news.views.article_detail'),
    url(r'^db/', include(admin.site.urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True)

projectroom/models.py
# django imports
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import floatformat
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _

# django-apps

from mptt.models import TreeForeignKey, MPTTModel, TreeManager

# python imports
import os

JOB_STATUS_CHOICES = (
    (1, _('Requested by Customer')),
    (2, _('Seen by Worker')),
    (3, _('Started by Worker')),
    (4, _('Cancelled by Worker')),
    (5, _('Cancelled by Customer')),
    (6, _('Waiting for Approval by Customer')),
    (7, _('Approved by Customer')),
    (8, _('Worker waiting to get Payed')),
    (9, _('Closed and finished by Worker'))
)

JOB_STATUS_LEN = len(JOB_STATUS_CHOICES)

CURRENCY_CHOICES = (
    ('EUR', _('Euro')),
    ('CHF', _('Swiss Francs')),
)


class JobType(models.Model):
    """
    i.e.: programming
    """
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name


class Company(models.Model):
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name


class Person(models.Model):
    user = models.OneToOneField(User)
    company = models.ForeignKey(Company)

    def __unicode__(self):
        un = self.user.get_full_name() or self.user.get_username()
        return un


class Project(models.Model):
    client_company = models.ForeignKey(Company)
    read_acl = models.ManyToManyField(Person, blank=True, related_name='project_readacl')
    write_acl = models.ManyToManyField(Person, blank=True, related_name='project_writeacl')
    name = models.CharField(max_length=255)
    slug = models.SlugField()
    active = models.BooleanField(default=True)

    def get_read_users(self):
        return User.objects.filter(person__project_readacl=self)

    def get_write_users(self):
        return User.objects.filter(person__project_writeacl=self)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ('client_company__name',)


class Account(models.Model):
    project = models.ForeignKey(Project)
    name = models.CharField(max_length=255)
    balance = models.DecimalField("Kontostand", decimal_places=2, max_digits=8, blank=True, null=True)
    currency = models.CharField(_('Currency'), max_length=3, choices=CURRENCY_CHOICES)

    def __unicode__(self):
        return self.name

    def calculate_balance(self):
        ai = self.accountentry_set.all().aggregate(values_sum=models.Sum('value'))
        values_sum = ai.get('values_sum')
        return values_sum


class AccountEntry(models.Model):
    account = models.ForeignKey(Account)
    value = models.DecimalField("Wert", decimal_places=2, max_digits=8)


class Rate(models.Model):
    """
    Rate per Client = Tarif
    """
    hourly_rate = models.DecimalField("Stundensatz", decimal_places=2, max_digits=8)
    initial_rate = models.DecimalField("Einmaliger Satz", decimal_places=2, max_digits=8)
    currency = models.CharField(_('Currency'), max_length=3, choices=CURRENCY_CHOICES)
    rate_of_taxation = models.DecimalField("Steuersatz", decimal_places=2, max_digits=8)

    def __unicode__(self):
        return _('%(hr)s %(c)s/h') % {
            'hr': floatformat(self.hourly_rate, 2),
            'c': self.get_currency_display()
        }


class JobManager(TreeManager):
    def open(self):
        return self.filter(ticket__status__lt=JOB_STATUS_LEN)


class Job(MPTTModel):
    project = models.ForeignKey(Project)
    job_type = models.ForeignKey(JobType, verbose_name=_('Job type'))
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', verbose_name=_('Parent Job'))
    name = models.CharField(max_length=255, verbose_name=_('Job name'))
    description = models.TextField(verbose_name=_('Description'))
    deadline = models.DateTimeField(verbose_name=_('Deadline'))
    rate = models.ForeignKey(Rate, verbose_name=_('Rate'))
    request_by = models.ForeignKey(Person, verbose_name=_('Requested by'))
    request_at = models.DateTimeField(verbose_name=_('Requested at'), auto_now_add=True)
    account = models.ForeignKey(Account, verbose_name=_('Account'))

    objects = JobManager()

    def get_path(self):
        return self.get_ancestors(include_self=True)

    def get_all_tickets(self):
        ticket_ids = []
        subjobs = self.get_descendants(include_self=True)
        for job in subjobs:
            ticket_ids.extend(job.ticket_set.all().values_list('pk', flat=True))
        return Ticket.objects.filter(pk__in=ticket_ids)

    def get_all_active_tickets(self):
        ticket_ids = []
        subjobs = self.get_descendants(include_self=True)
        for job in subjobs:
            ticket_ids.extend(job.ticket_set.active().values_list('pk', flat=True))
        return Ticket.objects.filter(pk__in=ticket_ids)

    def get_all_closed_tickets(self):
        ticket_ids = []
        subjobs = self.get_descendants(include_self=True)
        for job in subjobs:
            ticket_ids.extend(job.ticket_set.closed().values_list('pk', flat=True))
        return Ticket.objects.filter(pk__in=ticket_ids)

    def is_old_deadline(self):
        return self.deadline < timezone.now()

    def get_aggregated_duration_pre(self):
        return self.get_all_tickets().aggregate(sum_duration_pre=models.Sum('duration_pre')).get('sum_duration_pre') or 0

    def all_tickets_closed(self):
        all_tickets = self.get_all_tickets().count()
        if all_tickets > 0:
            return all_tickets == self.get_all_closed_tickets().count()
        return False

    @models.permalink
    def get_absolute_url(self):
        return ('job', [], {'pk': self.pk, 'project__slug': self.project.slug})

    @models.permalink
    def get_edit_url(self):
        return ('job_edit', [], {'pk': self.pk, 'project__slug': self.project.slug})

    def __unicode__(self):
        return self.name


class JobFile(models.Model):
    job = models.ForeignKey(Job)
    filefield = models.FileField(upload_to='jobfile', verbose_name=_('File'))
    description = models.TextField(null=True, blank=True, verbose_name=_('Description'))

    def is_image(self):
        if self.filefield:
            fn, ext = os.path.splitext(self.filefield.path)
            ext = ext.lower()
            if ext in ['.jpg', '.png']:
                return True
        return False

    def get_basename(self):
        if self.filefield:
            return os.path.basename(self.filefield.path)


class TicketManager(models.Manager):
    def active(self):
        return self.filter(status__lt=JOB_STATUS_LEN, hidden=False)

    def closed(self):
        return self.filter(status=JOB_STATUS_LEN, hidden=False)


class Ticket(models.Model):
    job = models.ForeignKey(Job)
    name = models.CharField(max_length=255, verbose_name=_('Ticket name'))
    status = models.IntegerField(choices=JOB_STATUS_CHOICES, verbose_name=_('Ticket status'))
    status_update = models.DateTimeField(null=True, blank=True)
    assigned_to = models.ForeignKey(Person, related_name='assigned_tickets', null=True, blank=True, verbose_name=_('Assigned to'))
    duration_pre = models.DecimalField(decimal_places=2, max_digits=8, null=True, blank=True, verbose_name=_('valued effort'))
    duration_post = models.DecimalField(decimal_places=2, max_digits=8, null=True, blank=True, verbose_name=_('actual effort'))

    hidden = models.BooleanField(default=False)

    objects = TicketManager()

    def update_status(self):
        tsc = TicketStatusChange.objects.filter(item__ticket=self).latest('item__created')
        self.status = tsc.post_status
        self.status_update = timezone.now()

    def progress(self):
        return float(self.status) / float(JOB_STATUS_LEN) * 100.0

    def progress_int(self):
        return int(self.progress())

    def progress_pipe(self):
        p = self.progress_int() / 10
        return mark_safe('|' * p + '&nbsp;' * (10 - p))

    def get_costs(self):
        duration_pre = self.duration_pre
        if duration_pre is None:
            duration_pre = 0
        return self.job.rate.hourly_rate * duration_pre

    def get_read_users(self):
        if self.hidden:
            return [self.assigned_to.user]
        else:
            return self.job.project.get_read_users()

    def is_closed(self):
        return self.status == 9

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('ticket', [], {'pk': self.pk, 'project__slug': self.job.project.slug, 'job__pk': self.job.pk})

    def get_last_ticketitem(self):
        return self.ticketitem_set.order_by('created').last()


class TicketItem(models.Model):
    ticket = models.ForeignKey(Ticket)
    creator = models.ForeignKey(Person)
    created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return _("%(ticket_name)s: %(creator)s %(created)s") % {'ticket_name': self.ticket.name, 'creator': self.creator, 'created': self.created}


class TicketText(models.Model):
    item = models.ForeignKey(TicketItem)
    text = models.TextField()


class TicketStatusChange(models.Model):
    item = models.ForeignKey(TicketItem)
    pre_status = models.IntegerField(choices=JOB_STATUS_CHOICES)
    post_status = models.IntegerField(choices=JOB_STATUS_CHOICES)

    def save(self, *args, **kwargs):
        super(TicketStatusChange, self).save(*args, **kwargs)
        self.item.ticket.update_status()
        self.item.ticket.save()

    def __unicode__(self):
        return _("%(ticket_name)s: %(pre)s to %(post)s") % {'ticket_name': self.item.ticket.name, 'pre': self.get_pre_status_display(), 'post': self.get_post_status_display()}


class TicketAccountEntry(models.Model):
    item = models.ForeignKey(TicketItem)
    accountentry = models.ForeignKey(AccountEntry)

projectroom/templates/projectroom/dashboard.html
{% extends 'projectroom/base.html' %}
{% load mptt_tags %}

{% block breadcrumbs %}
{% endblock %}


{% block js %}
<style type="text/css">

    #ticketitems {
        width: 45em;
    }

    #sidebar {
        float: right;
        width: 25em;
        background: #eee;
        padding: 1em;
        margin: 1em;
        border: 1px solid #aaa;

    }

</style>
{% endblock js %}

{% block content %}

<h2>Dashboard</h2>

<div id="sidebar" class="border-radius">
    <h3>Meine Projekte</h3>
    <ul>
        {% for project in my_projects %}
        <li><a href="{% url 'job_list' project__slug=project.slug %}">{{ project }}</a> <span class="small">{{ project.client_company }}</span></li>
        {% endfor %}
    </ul>

    <h3>Auswertung</h3>
    <ul>
        <li><a href="{% url 'closed_jobs' %}">Erledigte Aufgaben und Tickets</a></li>
    </ul>
    <p>&nbsp;</p>
    <p><a href="{% url 'project_list' %}" class="btn">Übersicht</a></p>
</div>

<div id="ticketitems">
    <h3>Neuste Änderungen</h3>
    {% for item in latest_ticketitems %}
    <div class="ticketitem">
        <p class="ticketitemmeta">Vor {{ item.created|timesince }} von {{ item.creator }} in <br/>
            <a href="{% url 'job_list' project__slug=item.ticket.job.project.slug %}">{{ item.ticket.job.project }}</a> /

            {% for job in item.ticket.job.get_path %}
            <a href="{{ job.get_absolute_url }}">{{ job }}</a>
            {% if not forloop.last %}
            &raquo;
            {% endif %}
            {% endfor %}
        </p>
        <p><a href="{{ item.ticket.get_absolute_url }}">Ticket #{{ item.ticket.pk }}: {{ item.ticket }}</a></p>

        {% if item.tickettext_set.exists %}
        <blockquote>Änderung:
            <q>{{ item.tickettext_set.first.text|truncatewords:8 }}</q>
        </blockquote>
        {% endif %}

        {% if item.ticketstatuschange_set.exists %}
        <blockquote>Status auf <q>{{ item.ticketstatuschange_set.first.get_post_status_display }}</q></blockquote>
        {% endif %}

        {% if item.ticketaccountentry_set.exists %}
        <blockquote>
            <p>
                Abbuchung von {{ item.ticketaccountentry_set.first.accountentry.value }} {{ item.ticketaccountentry_set.first.accountentry.get_currency_display }}
                von Konto {{ item.ticketaccountentry_set.first.accountentry.account }} erfolgt
            </p>
        </blockquote>
        {% endif %}
    </div>

    {% empty %}
    <p>Es existiert keine Ticketbeschreibung</p>
    {% endfor %}


</div>

<h3>Meine offenen Jobs und Tickets</h3>

<table>
    <tr>
        <th>Projekt</th>
        <th>Job</th>
        <th>AG</th>
        <th>Deadline</th>
        <th>Tickets</th>
    </tr>
    {% for job in my_open_jobs %}
    <tr>
        <td><a href="{% url 'job_list' project__slug=job.project.slug %}">{{ job.project }}</a></td>
        <td><a href="{{ job.get_absolute_url }}">{{ job }}</a></td>
        <td>{{ job.request_by }}</td>
        <td>
                            <span class="{% if job.is_old_deadline %}old-deadline{% endif %}">
                                {{ job.deadline|date:"SHORT_DATETIME_FORMAT" }}
                            </span>
        </td>
        <td>
            <ul>
                {% for ticket in job.get_all_active_tickets %}
                <li><span style="border: 1px solid black; font-size: small; padding: 2px;" title="{{ ticket.progress_int }} %">{{ ticket.progress_pipe }}</span> <a href="{% url 'ticket' project__slug=job.project.slug job__pk=job.pk pk=ticket.pk %}">{{ ticket }}</a></li>
                {% endfor %}
            </ul>
        </td>
    </tr>
    {% endfor %}
</table>



<div style="clear: both;"></div>


{% endblock %}

projectroom/templates/projectroom/job_detail.html
{% extends 'projectroom/base.html' %}

{% load mptt_tags %}

{% block breadcrumbs %}
<li><a href="{% url 'job_list' project__slug=object.project.slug %}">Aufträge {{ object.project }}</a></li>
{% for parent in object.get_ancestors %}
<li>
    <a href="{{ parent.get_absolute_url }}">{{ parent.name }}</a>
</li>
{% endfor %}
<li><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
{% endblock %}

{% block js %}
<script type="text/javascript">
    $(function () {
        $(".progressbar").progressbar({
            value: parseInt($(this).attr('data-value'), 10)
        });
    });
</script>
{% endblock js %}

{% block content %}

<div id="tabs">
    <ul>
        <li><a href="#details">Auftrags-Details</a></li>
        <li><a href="#filter">Filter nach Folgeaufträge / Teilaufträge ({{ object.get_descendant_count }})</a></li>
    </ul>

    <div id="details">
        <h2>Auftrag-Details</h2>

        <table>
            <tr>
                <th>Auftragsname</th>
                <td>{{ object.name }}</td>
            </tr>
            <tr>
                <th>Anfrage von</th>
                <td>{{ object.request_by }} am {{ object.request_at }}</td>
            </tr>
            <tr>
                <th style="vertical-align: top">Auftragbeschreibung</th>
                <td>
                    <blockquote>{{ object.description|urlize|linebreaksbr }}</blockquote>
                </td>
            </tr>
            <tr>
                <th>Deadline</th>
                <td>in {{ object.deadline|timeuntil }} ({{ object.deadline|date:'SHORT_DATETIME_FORMAT' }})</td>
            </tr>
            {% if user in object.project.get_write_users %}
            <tr>
                <th>Tarif</th>
                <td>{{ object.rate }}</td>
            </tr>

            <tr>
                <th>Dateien</th>
                <td>
                    <ul>
                        {% for jf in object.jobfile_set.all %}
                            {% if jf.is_image %}
                                <li><a data-lightbox="ticketfile" href="{{ jf.filefield.url }}"><img src="{{ jf.filefield.url }}" style="max-height: 50px; max-width: 50px;"></a></li>
                            {% else %}
                                <li><a href="{{ jf.filefield.url }}" target="_blank">{{ jf.get_basename }}</a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </td>
            </tr>

            <tr>
                <th>Veranschlagte Zeit</th>
                <td>{{ object.get_aggregated_duration_pre }} Stunde(n)</td>
            </tr>

            <tr>
                <td colspan="2"><a href="{{ object.get_edit_url }}" class="btn">Auftragsdetails bearbeiten</a></td>
            </tr>
            {% endif %}
        </table>

    </div>


    <div id="filter">
        <h2>Filter nach Folgeaufträge / Teilaufträge ({{ object.get_descendant_count }})</h2>

        {% if object.get_descendants %}
        <ul class="default">
            {% recursetree object.get_descendants %}
            <li>

                <a href="{{ node.get_absolute_url }}">{{ node.name }}</a>


                {% if not node.is_leaf_node %}
                <ul class="children">
                    {{ children }}
                </ul>
                {% endif %}
            </li>
            {% endrecursetree %}
        </ul>
        {% else %}
        <p>Keine</p>
        {% endif %}

        <p><a class="btn" href="{{ object.get_root.get_absolute_url }}">Filter zurücksetzen</a></p>
    </div>
</div>


<h2>Tickets/Teilaufgaben innerhalb {{ object.name }} ({{ object.get_all_tickets.count }})</h2>
<table>
    <thead>
    <tr>
        <th>#</th>
        <th>Auftrag</th>
        <th>Ticket</th>
        <th>Status</th>
        <th>AG</th>
        <th>AN</th>
        <th>Fortschritt</th>
        <th>Veranschl.</th>
    </tr>
    </thead>
    <tbody>

    {% for ticket in tickets %}
    <tr class="{% if ticket.is_closed %}ticket-close{% endif %}">
        <td>#{{ ticket.pk }}</td>
        <td>
            <a href="{{ ticket.job.get_absolute_url }}" title="{% for j in ticket.job.get_ancestors %}{{ j }} &gt {% endfor %} {{ ticket.job }}">
                {% for j in ticket.job.get_ancestors %}
                {{ j|truncatechars:5 }} &gt;
                {% endfor %}

                {{ ticket.job|truncatechars:20 }}</a></td>
        <td><a href="{{ ticket.get_absolute_url }}">{{ ticket.name }}</a></td>
        <td>{{ ticket.get_status_display }}</td>
        <td>{{ ticket.job.request_by }}</td>
        <td>{{ ticket.assigned_to }}</td>
        <td>
            <div class="progressbar" data-value="{{ ticket.progress_int }}">
                <div class="progress-label">{{ ticket.progress_int }}%</div>

            </div>
        </td>
        <td>
            {{ ticket.duration_pre }} h
        </td>
    </tr>

    {% empty %}
    <tr>
        <td colspan="4">Der Auftrag wartet auf die Bearbeitung.</td>
    </tr>
    {% endfor %}
    {% if user in object.project.get_write_users %}
    <tr>
        <td colspan="4"><a class="btn" href="{% url 'ticket_add' project__slug=object.project.slug pk=object.pk %}">Ticket erstellen</a></td>
    </tr>
    {% endif %}
    </tbody>
</table>

{% endblock %}

projectroom/templates/projectroom/logout.html
{% extends 'projectroom/base.html' %}

{% block content %}
    <p>Abgemeldet. Bis zum nächsten Mal!</p>
{% endblock %}

projectroom/templates/projectroom/project_list.html
{% extends 'projectroom/base.html' %}
{% load mptt_tags %}

{% block breadcrumbs %}

{% endblock %}


{% block content %}

    <h2>Projektliste</h2>

    <table>
    <thead>
    <tr>
        <th>Firma</th>
        <th>Projekt</th>
        <th>offene Aufträge</th>
        <th>Aufträge und Tickets</th>
    </tr>
    </thead>
    <tbody>

    {% for project in object_list %}

        <tr>
            <td>{{ project.client_company }}</td>
            <td>{{ project.name }}</td>
            <td><a href="{% url 'job_list' project__slug=project.slug %}">{{ project.job_set.open.count }}</a></td>
            <td>
                <ul class="default">
                    {% recursetree project.job_set.all %}
                        <li>
                            <a href="{{ node.get_absolute_url }}">
                                {{ node.name }}
                            </a>
                            <ul class="tickets">
                                {% for ticket in node.ticket_set.active %}
                                    <li><a href="{{ ticket.get_absolute_url }}">{{ ticket }}</a> <span class="small"> ({{ ticket.get_status_display }})</span></li>
                                {% endfor %}
                            </ul>

                            {% if not node.is_leaf_node %}
                                <ul class="children">
                                    {{ children }}
                                </ul>
                            {% endif %}
                        </li>
                    {% endrecursetree %}
                </ul>
            </td>
        </tr>

    {% endfor %}
    </tbody>
    </table>

{% endblock %}

projectroom/templates/projectroom/ticket_detail.html
{% extends 'projectroom/base.html' %}

{% block breadcrumbs %}
<li><a href="{% url 'job_list' project__slug=object.job.project.slug %}">{{ object.job.project }}</a></li>
{% for parent in object.job.get_ancestors %}
<li>
    <a href="{{ parent.get_absolute_url }}">{{ parent.name }}</a>
</li>
{% endfor %}
<li><a href="{{ object.job.get_absolute_url }}">{{ object.job }}</a></li>
<li><a href="">{{ object }}</a></li>
{% endblock %}

{% block content %}

<h2>Ticket #{{ object.pk }}: {{ object.name }}</h2>

<div id="tabs">
    <ul>
        <li><a href="#details">Ticket-Details</a></li>
    </ul>

    <div id="details">

        <table>
            <tr>
                <th>Status</th>
                <td>{{ object.get_status_display }} ({{ object.progress|floatformat }}%)</td>
                <th>Auftraggeber</th>
                <td>{{ object.job.request_by }}</td>
                <th>Auftragnehmer</th>
                <td>{{ object.assigned_to }} {% if assigned_to_me %}<strong>*ich*</strong>{% endif %}</td>
            </tr>
            <tr>
                <th>Veranschlagte Zeit</th>
                <td>{{ object.duration_pre }} h</td>
                <th>Tatsächliche Zeit</th>
                <td>{{ object.duration_post|default:0 }} h</td>
                <th>Tarif</th>
                <td>{{ object.job.rate }}</td>
            </tr>
            <tr>
                <th>Veranschlagte Kosten</th>
                <td colspan="4">
                    {{ object.duration_pre|floatformat:2 }}h * {{ object.job.rate }} = {{ object.get_costs|floatformat:2 }} {{ object.job.rate.get_currency_display }}
                </td>
            </tr>
            {% if assigned_to_me %}
            <tr>
                <td colspan="6">

                    <a href="{% url 'ticket_edit' project__slug=object.job.project.slug job__pk=object.job.pk pk=object.pk %}" class="btn">Ticket anpassen</a>

                </td>
            </tr>
            {% endif %}


        </table>

    </div>


</div>


<h2>Verlauf</h2>


{% for item in object.ticketitem_set.all %}
    <p class="ticketitemmeta">Erstellt vor {{ item.created|timesince }} von {{ item.creator }} am {{ item.created }} Uhr</p>
    {% for text in item.tickettext_set.all %}
        <pre>{{ text.text }}</pre>
    {% endfor %}

    {% for sc in item.ticketstatuschange_set.all %}
        <pre class="statuschange small">Der Status wurde von <i>{{ sc.get_pre_status_display }}</i> auf <strong>{{ sc.get_post_status_display }}</strong> geändert.</pre>
    {% endfor %}

    {% for tae in item.ticketaccountentry_set.all %}
        <pre class="accountentry">Abbuchung von {{ tae.accountentry.value }} {{ tae.accountentry.account.get_currency_display }} von Konto {{ tae.accountentry.account }}</pre>
    {% endfor %}

{% empty %}
    <p>Es existiert keine Ticketbeschreibung</p>
{% endfor %}


<h2>Ticketeintrag hinzufügen</h2>
{% if user in object.job.project.get_read_users %}
<form action="{% url 'ticketitem_add' project__slug=object.job.project.slug job__pk=object.job.pk pk=object.pk %}" method="post">
    {% csrf_token %}
    {% include 'projectroom/includes/djangoform_table.html' with form=ticket_form %}
    <input class="btn" type="submit" value="Ticketeintrag hinzufügen"/>
</form>

{% else %}
<p>Zugriff verweigert.</p>
{% endif %}


{% endblock %}